# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "box-cutter/ubuntu1404-desktop"
  config.vm.network "forwarded_port", guest: 9878, host: 9878
  config.vm.network "private_network", ip: "192.168.56.121"
  config.vm.hostname = "postgresql-hosting"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    vb.name = "postgresql-hosting-vm"

    # Customize the amount of memory on the VM:
    vb.memory = "4096"
    vb.cpus = 2
  end

  # Installs all packages and tools 
  config.vm.provision :shell, path: "psql_setup.sh"

end