# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('path_setup', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nProject.nProject')),
            ],
        ),
    ]
