# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nPath', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npath',
            name='project',
        ),
        migrations.AlterField(
            model_name='npath',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='npath',
            name='path_setup',
            field=models.TextField(default=''),
        ),
    ]
