# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nStatusComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='nStatusComponentLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='nStatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='nstatuscomponent',
            name='status_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nTracking.nStatusComponentLevel'),
        ),
        migrations.AddField(
            model_name='nstatuscomponent',
            name='status_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nTracking.nStatusType'),
        ),
    ]
