# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import nTracking.models
import noctis.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nTracking', '0002_auto_20160315_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nstatustype',
            name='total_status_components',
        ),
        migrations.AlterField(
            model_name='nstatuscomponentlevel',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='nstatustype',
            name='status_breakdown',
            field=noctis.fields.ListField(default=['Not Started', 'Started', 'Work In Progress', 'In Review', 'Approved', 'Completed'], validators=[nTracking.models.statusBreakdownTest]),
        ),
    ]
