# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 03:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nProject', '0005_auto_20160415_0327'),
        ('nAsset', '0007_auto_20160415_0327'),
        ('nTracking', '0003_auto_20160316_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='nAbstractApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_on', models.DateTimeField(default=datetime.datetime.now)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='nApprovalLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='nstatustype',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='nMainApproval',
            fields=[
                ('nabstractapproval_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nTracking.nAbstractApproval')),
                ('asset_pointer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nAsset.nAsset')),
                ('hub_pointer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nProject.nProjectHub')),
                ('part_pointer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nProject.nProjectPart')),
                ('project_pointer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nProject.nProject')),
            ],
            bases=('nTracking.nabstractapproval',),
        ),
        migrations.AddField(
            model_name='nabstractapproval',
            name='approval_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nTracking.nApprovalLevel'),
        ),
    ]
