# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('nAsset', '0001_initial'), ('nAsset', '0002_auto_20160216_0036'), ('nAsset', '0003_auto_20160224_1320'), ('nAsset', '0004_auto_20160225_0455'), ('nAsset', '0005_auto_20160307_1253'), ('nAsset', '0006_auto_20160315_1205'), ('nAsset', '0007_auto_20160415_0327'), ('nAsset', '0008_auto_20160415_0329'), ('nAsset', '0009_remove_nasset_project_hub')]

    initial = True

    dependencies = [
        ('nProject', '0003_auto_20160225_0455'),
        ('nPath', '0001_initial'),
        ('nProject', '0005_auto_20160415_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='nAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('asset_pointer', models.CharField(default='', max_length=300)),
                ('asset_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nAsset.nObjectType')),
                ('version', models.IntegerField(default=0)),
                ('asset_name', models.CharField(default='', max_length=300)),
                ('path_setup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nPath.nPath')),
                ('project_part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nProject.nProjectPart')),
            ],
        ),
        migrations.CreateModel(
            name='nAssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='nVersionControler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='', max_length=64)),
                ('highest_version', models.IntegerField(default=1)),
                ('asset_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nAsset.nAssetType')),
                ('hub_pointer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nProject.nProjectHub')),
            ],
        ),
        migrations.AddField(
            model_name='nasset',
            name='version_controller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nAsset.nVersionControler'),
        ),
        migrations.RemoveField(
            model_name='nasset',
            name='asset_name',
        ),
        migrations.RemoveField(
            model_name='nasset',
            name='name',
        ),
        migrations.RemoveField(
            model_name='nasset',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='nasset',
            name='path_setup',
        ),
        migrations.RemoveField(
            model_name='nasset',
            name='project_part',
        ),
        migrations.AddField(
            model_name='nasset',
            name='author',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='nversioncontroler',
            unique_together=set([('hub_pointer', 'group_name', 'asset_type')]),
        ),
        migrations.RenameModel(
            old_name='nVersionControler',
            new_name='nVersionController',
        ),
    ]
