# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nAsset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasset',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nasset',
            name='version_group_id',
            field=models.IntegerField(default=0),
        ),
    ]
