# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nProject', '0003_auto_20160225_0455'),
        ('nAsset', '0003_auto_20160224_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nasset',
            old_name='object_name',
            new_name='asset_name',
        ),
        migrations.RenameField(
            model_name='nasset',
            old_name='object_pointer',
            new_name='asset_pointer',
        ),
        migrations.RenameField(
            model_name='nasset',
            old_name='object_type',
            new_name='asset_type',
        ),
        migrations.AddField(
            model_name='nasset',
            name='project_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nProject.nProjectPart'),
        ),
    ]
