
# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nAsset', '0005_auto_20160307_1253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='nObjectType',
            new_name='nAssetType',
        ),
        migrations.RenameField(
            model_name='nasset',
            old_name='version_group',
            new_name='version_controller',
        ),
        migrations.RemoveField(
            model_name='nasset',
            name='asset_name',
        ),
        migrations.RemoveField(
            model_name='nasset',
            name='name',
        ),
        migrations.AddField(
            model_name='nversioncontroler',
            name='group_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='nversioncontroler',
            name='highest_version',
            field=models.IntegerField(default=0),
        ),
    ]