# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nAsset', '0007_auto_20160415_0327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='nVersionControler',
            new_name='nVersionController',
        ),
    ]
