# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "box-cutter/ubuntu1404-desktop"
  config.vm.hostname = "noctis-django-hosting"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    vb.name = "noctis-django-hosting-vm"

    # Customize the amount of memory on the VM:
    vb.memory = "4096"
    vb.cpus = 2
  end

  # Installs all packages and tools 
  config.vm.provision :shell, path: "noctis_setup.sh"

end