# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nProject', '0002_nproject_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='nProjectHub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='nProjectPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='nProjectPartType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='nProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='nprojectpart',
            name='part_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nProject.nProjectPartType'),
        ),
        migrations.AddField(
            model_name='nprojecthub',
            name='part_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nProject.nProjectPartType'),
        ),
        migrations.AddField(
            model_name='nproject',
            name='project_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nProject.nProjectType'),
        ),
    ]
