# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nTracking', '0001_initial'),
        ('nProject', '0003_auto_20160225_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='nprojectpart',
            name='track_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nTracking.nStatusComponent'),
        ),
        migrations.AlterField(
            model_name='nproject',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='nprojecthub',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='nprojectpart',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='nprojectparttype',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='nprojecttype',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
